#! /usr/bin/python
# coding:utf-8
# 空水瓶问题

while 1:
    try:
        empty = int(input())
        if empty:
            total = 0
            while empty >= 3:
                exchange = empty // 3
                empty = exchange + empty % 3
                total += exchange
            if empty == 2:
                total = total + 1
            print total
        else:
            break
    except:
        break
# 总结：用两个空水两瓶换一个，总数除以2即可

# 去重与排序
while 1:
    try:
        numer = int(input())
        array = []
        for num in range(0, numer):
            temp = int(input())
            array.append(temp)
        array_1 = []
        for i in array:
            if not i in array_1:
                array_1.append(i)
        array_1.sort()
        for item in array_1:
            print item
    except:
        break

# 总结：使用列表数据结构，遍历去重后调用python内置sort函数排序

# 十六进制转十进制
# 进制转换

while 1:
    try:
        h = input()
        print h, bin(h), oct(h)
    except:
        break

# 总结：python是一个强大的工具

